{
  "swagger" : "2.0",
  "info" : {
    "description" : "RESTful API for the Denner Wineshop",
    "version" : "1.0.0",
    "title" : "Denner Shop Web Service",
    "contact" : {
      "name" : "DETAIL NET",
      "email" : "support+denner-shop-api@detailnet.ch"
    }
  },
  "host" : "denner-shop-api-v1.detailnet.ch",
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/sweepstake-participants" : {
      "post" : {
        "tags" : [ "other" ],
        "summary" : "Create a new sweepstake participant",
        "description" : "Use this operation to create a sweepstake participant (Gewinnspielteilnehmer).\n",
        "operationId" : "createSweepstakeParticipant",
        "parameters" : [ {
          "name" : "Accept",
          "in" : "header",
          "description" : "Accepted content type (supported is \"application/json\")\n",
          "required" : false,
          "type" : "string",
          "default" : "application/json"
        }, {
          "name" : "Content-Type",
          "in" : "header",
          "description" : "Request body content type (supported is \"application/json\")\n",
          "required" : false,
          "type" : "string",
          "default" : "application/json"
        }, {
          "in" : "body",
          "name" : "participant",
          "description" : "Data for the participant\n",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/NewSweepstakeParticipant"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Successful creation",
            "schema" : {
              "$ref" : "#/definitions/SweepstakeParticipant"
            },
            "examples" : {
              "application/json" : {
                "id" : "ed20c828-17b4-4a19-b403-ae223e1cfece",
                "created_on" : "2016-05-09T13:30:29+00:00",
                "display_name" : "Michelle M.",
                "city" : "Zurich",
                "language" : "de"
              }
            }
          }
        },
        "security" : [ {
          "appKey" : [ ]
        } ]
      }
    },
    "/wines" : {
      "get" : {
        "tags" : [ "wine" ],
        "summary" : "List all wines currently targetted for the Wineshop",
        "description" : "Use this operation to get a list of all wines targetted for the Wineshop.\n",
        "operationId" : "listWines",
        "parameters" : [ {
          "name" : "filter",
          "in" : "query",
          "description" : "Filters: JSON array of Filter object, urlencoded.\n\nFilter object:\n- property: Property to filter on.\n- operator: Operation property. Enumeration ('eq', 'like', 'lt', 'gt', 'in', ...). Dependent from property (not all might be allowed).\n- type: Type of value. Enumeration ('string', 'integer', 'boolean', 'array') Dependent from property and operator (not all might be allowed).\n- value: Value. Must be of the defined type.\n\nExamples:\n- [{\"property\":\"id\",\"operator\":\"in\",\"type\":\"array\",\"value\":[\"7627150d-36bd-4867-89b2-091800a03d24\",\"58afec5c-ece9-4b66-bc55-00d6dc1b65b8\"]}]\n- [{\"property\":\"in_shop\",\"operator\":\"eq\",\"type\":\"boolean\",\"value\":true}]\n",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "page",
          "in" : "query",
          "description" : "The page number. Default: 1\n",
          "required" : false,
          "type" : "integer",
          "default" : 1,
          "minimum" : 0.0,
          "format" : "int32"
        }, {
          "name" : "page_size",
          "in" : "query",
          "description" : "The page size. Default: 10\nTo disable pagination (when supported) send \"-1\".\n",
          "required" : false,
          "type" : "integer",
          "default" : 10,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful listing",
            "schema" : {
              "$ref" : "#/definitions/ArticlesResponse"
            },
            "examples" : {
              "application/json" : {
                "page_count" : 1,
                "page_size" : 1,
                "total_items" : 1,
                "articles" : [ {
                  "id" : "051273",
                  "name" : "Mandorla Primitivo IGT Puglia",
                  "title" : [ {
                    "locale" : "de",
                    "value" : "Mandorla Primitivo di Puglia IGT"
                  }, {
                    "locale" : "fr",
                    "value" : "Mandorla Primitivo di Puglia IGT"
                  }, {
                    "locale" : "it",
                    "value" : "Mandorla Primitivo di Puglia IGT"
                  } ],
                  "description" : [ {
                    "locale" : "de",
                    "value" : "2013, Apulien, Italien, 6 x 75 cl"
                  }, {
                    "locale" : "fr",
                    "value" : "2013, les Pouilles, Italie, 6 x 75 cl"
                  }, {
                    "locale" : "it",
                    "value" : "2013, Puglia, Italia, 6 x 75 cl"
                  } ],
                  "article_group" : {
                    "id" : "0c309757-5432-4652-8201-ec35f31c5260",
                    "code" : "60-56",
                    "name" : "Italien Rot 70 cl",
                    "parent" : {
                      "id" : "3f3df00f-6a7e-49a9-8eca-a36727ca4977",
                      "code" : "60",
                      "name" : "Weine"
                    }
                  },
                  "barcodes" : [ {
                    "value" : "086003000094",
                    "type" : "UPC12",
                    "quantity" : 1,
                    "master" : false
                  }, {
                    "value" : "086003004344",
                    "type" : "UPC12",
                    "quantity" : 6,
                    "master" : false
                  }, {
                    "value" : "5010186016172",
                    "type" : "EAN13",
                    "quantity" : 1,
                    "master" : true
                  }, {
                    "value" : "0860030043442",
                    "type" : "EAN13",
                    "quantity" : 6,
                    "master" : true
                  } ],
                  "content" : {
                    "size" : 0.75,
                    "label" : [ {
                      "locale" : "de",
                      "value" : "cl"
                    }, {
                      "locale" : "fr",
                      "value" : "cl"
                    }, {
                      "locale" : "it",
                      "value" : "cl"
                    } ],
                    "text" : [ {
                      "locale" : "de",
                      "value" : "75 cl"
                    }, {
                      "locale" : "fr",
                      "value" : "75 cl"
                    }, {
                      "locale" : "it",
                      "value" : "75 cl"
                    } ]
                  },
                  "base" : {
                    "text" : [ {
                      "locale" : "de",
                      "value" : "10 cl"
                    }, {
                      "locale" : "fr",
                      "value" : "10 cl"
                    }, {
                      "locale" : "it",
                      "value" : "10 cl"
                    } ]
                  },
                  "eco_labels" : [ {
                    "id" : "66d94617-bbd7-477e-ae66-183deb67ba5b",
                    "code" : "bio",
                    "name" : "Bio"
                  } ],
                  "wine" : {
                    "country" : {
                      "id" : "IT",
                      "title" : [ {
                        "locale" : "de",
                        "value" : "Italien"
                      }, {
                        "locale" : "fr",
                        "value" : "Italie"
                      }, {
                        "locale" : "it",
                        "value" : "Italia"
                      } ],
                      "flag" : {
                        "image_url" : "https://denner-assets.s3-eu-west-1.amazonaws.com/flags/IT.png"
                      }
                    },
                    "region" : {
                      "id" : "b19c42bf-ed78-46ff-ad6f-fc688a059e6a",
                      "title" : [ {
                        "locale" : "de",
                        "value" : "Apulien"
                      }, {
                        "locale" : "fr",
                        "value" : "Les Pouilles"
                      }, {
                        "locale" : "it",
                        "value" : "Puglia"
                      } ]
                    },
                    "type" : {
                      "id" : 2,
                      "title" : [ {
                        "locale" : "de",
                        "value" : "Rotwein"
                      }, {
                        "locale" : "fr",
                        "value" : "Vin rouge"
                      }, {
                        "locale" : "it",
                        "value" : "Vino rosso"
                      } ]
                    },
                    "online_specials" : [ {
                      "id" : "wine",
                      "sort_index" : 10,
                      "title" : [ {
                        "locale" : "de",
                        "value" : "Weine"
                      }, {
                        "locale" : "fr",
                        "value" : "Vins"
                      }, {
                        "locale" : "it",
                        "value" : "Vini"
                      } ]
                    } ],
                    "year" : 2013,
                    "fits_with" : [ {
                      "locale" : "de",
                      "value" : "Pasta, Fleisch mit würzigen Saucen"
                    }, {
                      "locale" : "fr",
                      "value" : "Pâtes, viande aux sauces relevées"
                    }, {
                      "locale" : "it",
                      "value" : "Pasta, carni accompagnate da salse aromatiche"
                    } ],
                    "varietal" : [ {
                      "locale" : "de",
                      "value" : "Primitivo"
                    }, {
                      "locale" : "fr",
                      "value" : "Primitivo"
                    }, {
                      "locale" : "it",
                      "value" : "Primitivo"
                    } ],
                    "character" : [ {
                      "locale" : "de",
                      "value" : "Dunkles Rubinrot. In der Nase Aromen von roten Beeren, reifen Kirschen und Brombeeren. Geschmeidig im Gaumen."
                    }, {
                      "locale" : "fr",
                      "value" : "Robe rubis foncé. Nez de baies rouges, de cerises matures et de mûres. Bouche moelleuse."
                    }, {
                      "locale" : "it",
                      "value" : "Rosso rubino scuro. Al naso aromi di bacche rosse, ciliege mature e more. Morbido al palato."
                    } ],
                    "temperature" : [ {
                      "locale" : "de",
                      "value" : "16-18 °C"
                    }, {
                      "locale" : "fr",
                      "value" : "16-18 °C"
                    }, {
                      "locale" : "it",
                      "value" : "16-18 °C"
                    } ],
                    "awards" : [ {
                      "locale" : "de",
                      "value" : ""
                    }, {
                      "locale" : "fr",
                      "value" : ""
                    }, {
                      "locale" : "it",
                      "value" : ""
                    } ],
                    "storage" : [ {
                      "locale" : "de",
                      "value" : "3 Jahre"
                    }, {
                      "locale" : "fr",
                      "value" : "3 ans"
                    }, {
                      "locale" : "it",
                      "value" : "3 anni"
                    } ],
                    "rating" : {
                      "value" : 4.45,
                      "total" : 11,
                      "valid" : true
                    },
                    "shop" : {
                      "url" : "http://denner-wineshop.ch/skuredirect/051273/",
                      "stock" : {
                        "value" : -15,
                        "code" : 2,
                        "message" : [ {
                          "locale" : "de",
                          "value" : "Derzeit nicht bestellbar"
                        }, {
                          "locale" : "fr",
                          "value" : "Actuellement pas disponible"
                        }, {
                          "locale" : "it",
                          "value" : "Attualmente non disponibile"
                        } ]
                      },
                      "quantity" : 6,
                      "prices" : {
                        "sales" : 59.4,
                        "instead" : 68.4,
                        "final" : true,
                        "by_quantity" : [ {
                          "quantity" : 1,
                          "sales" : 9.9,
                          "instead" : 11.4,
                          "final" : true
                        }, {
                          "quantity" : 6,
                          "sales" : 59.4,
                          "instead" : 68.4,
                          "final" : true
                        } ]
                      },
                      "discount" : [ {
                        "locale" : "de",
                        "value" : "13%"
                      }, {
                        "locale" : "fr",
                        "value" : "13%"
                      }, {
                        "locale" : "it",
                        "value" : "13%"
                      } ],
                      "packshot" : {
                        "id" : "5983a33d-ac61-49a8-a836-43259e78e9d0",
                        "url" : "https://denner-assets.s3-eu-west-1.amazonaws.com/assets/5983a33d-ac61-49a8-a836-43259e78e9d0/051273_6.png",
                        "cdn_url" : "https://denner.imgix.net/assets/5983a33d-ac61-49a8-a836-43259e78e9d0/051273_6.png",
                        "quantity" : 6,
                        "created_on" : "2016-01-07T15:42:19+02:00"
                      }
                    },
                    "box" : {
                      "code" : "KA",
                      "batch_size" : 3
                    }
                  }
                } ]
              }
            }
          }
        },
        "security" : [ {
          "appKey" : [ ]
        } ]
      }
    },
    "/wines/{article_id}/appraisals" : {
      "get" : {
        "tags" : [ "wine" ],
        "summary" : "List the appraisals of given wine",
        "description" : "Use this operation to get a list of all appraisals (Bewertungen) for a specific wine.\n",
        "operationId" : "listAppraisalsByWine",
        "parameters" : [ {
          "name" : "Accept",
          "in" : "header",
          "description" : "Accepted content type (supported is \"application/json\")\n",
          "required" : false,
          "type" : "string",
          "default" : "application/json"
        }, {
          "name" : "article_id",
          "in" : "path",
          "description" : "The unique identifier of an article",
          "required" : true,
          "type" : "string",
          "pattern" : "/^\\d{6}$/"
        }, {
          "name" : "page",
          "in" : "query",
          "description" : "The page number. Default: 1\n",
          "required" : false,
          "type" : "integer",
          "default" : 1,
          "minimum" : 0.0,
          "format" : "int32"
        }, {
          "name" : "page_size",
          "in" : "query",
          "description" : "The page size. Default: 10\nTo disable pagination (when supported) send \"-1\".\n",
          "required" : false,
          "type" : "integer",
          "default" : 10,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful listing",
            "schema" : {
              "$ref" : "#/definitions/AppraisalsResponse"
            },
            "examples" : {
              "application/json" : {
                "total_appraisals" : 15,
                "appraisals" : [ {
                  "id" : "7063984c-4eea-4abe-825b-e80612ba89c3",
                  "created_on" : "2015-10-30T10:16:41+02:00",
                  "wine_year" : 2013,
                  "title" : "un très très bon vin",
                  "description" : "mais ce n'est pas du zinfandel !! c'est du PRIMITIVO !! le cépage ORIGINAL !!! Denner, qu'est ce qui vous arrive ???",
                  "rating" : 5,
                  "display_name" : "Hans M.",
                  "city" : "Cossonay",
                  "language" : "fr"
                }, {
                  "id" : "a8c82c69-e975-4d3b-b0ba-aae6ed961cd7",
                  "created_on" : "2015-10-20T14:37:56+02:00",
                  "wine_year" : null,
                  "title" : "Ein Primitivo passt immer.",
                  "description" : null,
                  "rating" : 4,
                  "display_name" : "Michelle M.",
                  "city" : "Zürich",
                  "language" : "de"
                } ]
              }
            }
          }
        },
        "security" : [ {
          "appKey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "wine" ],
        "summary" : "Create a new appraisal for the given wine",
        "description" : "Use this operation to create a new appraisal (Bewertung) for a specific wine.\n",
        "operationId" : "createAppraisal",
        "parameters" : [ {
          "name" : "Accept",
          "in" : "header",
          "description" : "Accepted content type (supported is \"application/json\")\n",
          "required" : false,
          "type" : "string",
          "default" : "application/json"
        }, {
          "name" : "Content-Type",
          "in" : "header",
          "description" : "Request body content type (supported is \"application/json\")\n",
          "required" : false,
          "type" : "string",
          "default" : "application/json"
        }, {
          "name" : "article_id",
          "in" : "path",
          "description" : "The unique identifier of an article",
          "required" : true,
          "type" : "string",
          "pattern" : "/^\\d{6}$/"
        }, {
          "in" : "body",
          "name" : "appraisal",
          "description" : "Data for the appraisal\n",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/NewAppraisal"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Successful creation",
            "schema" : {
              "$ref" : "#/definitions/Appraisal"
            },
            "examples" : {
              "application/json" : {
                "id" : "7063984c-4eea-4abe-825b-e80612ba89c3",
                "created_on" : "2015-10-30T10:16:41+02:00",
                "wine_year" : 2013,
                "title" : "un très très bon vin",
                "description" : "mais ce n'est pas du zinfandel !! c'est du PRIMITIVO !! le cépage ORIGINAL !!! Denner, qu'est ce qui vous arrive ???",
                "rating" : 5,
                "display_name" : "Hans M.",
                "city" : "Cossonay",
                "language" : "fr"
              }
            }
          }
        },
        "security" : [ {
          "appKey" : [ ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "appKey" : {
      "type" : "apiKey",
      "name" : "App-Key",
      "in" : "header"
    }
  },
  "definitions" : {
    "UUIDv4" : {
      "type" : "string",
      "description" : "Unique identifier"
    },
    "SortIndex" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Index for sorting"
    },
    "Locale" : {
      "type" : "string",
      "description" : "Locale"
    },
    "Translation" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "$ref" : "#/definitions/Locale"
        },
        "value" : {
          "type" : "string",
          "description" : "Translated text value"
        }
      }
    },
    "Url" : {
      "type" : "string",
      "description" : "Web URL address"
    },
    "CountryFlag" : {
      "type" : "object",
      "properties" : {
        "image_url" : {
          "$ref" : "#/definitions/Url"
        }
      },
      "description" : "Country flag"
    },
    "Country" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Country code definition from ISO 3166",
          "pattern" : "/^[A-Z]{2}$/"
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        },
        "flag" : {
          "$ref" : "#/definitions/CountryFlag"
        }
      },
      "description" : "Country"
    },
    "Date" : {
      "type" : "string",
      "format" : "date",
      "description" : "Date; Format full-date of RFC3339 (http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14)"
    },
    "Year" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Year"
    },
    "Price" : {
      "type" : "number",
      "format" : "float",
      "description" : "Price in CHF"
    },
    "Quantity" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Quantity"
    },
    "ContentSize" : {
      "type" : "number",
      "format" : "float",
      "description" : "Content size"
    },
    "AssignedArticleGroup" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "code" : {
          "type" : "string",
          "description" : "Navision article group code (e.g. '01', '20', '01-60', '38-998')",
          "pattern" : "/^\\d{2}(-\\d{2,3})?$/"
        },
        "name" : {
          "type" : "string",
          "description" : "Article group name"
        },
        "parent" : {
          "$ref" : "#/definitions/AssignedArticleGroup"
        }
      }
    },
    "EcoLabel" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "code" : {
          "type" : "string",
          "description" : "Navision identification code"
        },
        "name" : {
          "type" : "string",
          "description" : "German name for the eco label"
        }
      }
    },
    "Article" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Navision article code",
          "pattern" : "/^\\d{6}$/"
        },
        "name" : {
          "type" : "string",
          "description" : "Article name"
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        },
        "description" : {
          "$ref" : "#/definitions/Translations"
        },
        "article_group" : {
          "$ref" : "#/definitions/AssignedArticleGroup"
        },
        "barcodes" : {
          "$ref" : "#/definitions/Barcodes"
        },
        "content" : {
          "$ref" : "#/definitions/Content"
        },
        "base" : {
          "$ref" : "#/definitions/BaseContent"
        },
        "eco_labels" : {
          "$ref" : "#/definitions/EcoLabels"
        },
        "wine" : {
          "$ref" : "#/definitions/ArticleWine"
        }
      }
    },
    "ArticlePrices" : {
      "type" : "object",
      "properties" : {
        "sales" : {
          "$ref" : "#/definitions/Price"
        },
        "list" : {
          "$ref" : "#/definitions/Price"
        },
        "instead" : {
          "$ref" : "#/definitions/Price"
        },
        "base" : {
          "$ref" : "#/definitions/Price"
        },
        "final" : {
          "type" : "boolean",
          "description" : "Is the price final?"
        },
        "by_quantity" : {
          "$ref" : "#/definitions/QuantityPrices"
        }
      }
    },
    "QuantityPrices" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/QuantityPrice"
      }
    },
    "QuantityPrice" : {
      "type" : "object",
      "properties" : {
        "quantity" : {
          "$ref" : "#/definitions/Quantity"
        },
        "sales" : {
          "$ref" : "#/definitions/Price"
        },
        "list" : {
          "$ref" : "#/definitions/Price"
        },
        "instead" : {
          "$ref" : "#/definitions/Price"
        },
        "final" : {
          "type" : "boolean",
          "description" : "Is the price final?"
        }
      }
    },
    "Content" : {
      "type" : "object",
      "properties" : {
        "size" : {
          "$ref" : "#/definitions/ContentSize"
        },
        "label" : {
          "$ref" : "#/definitions/Translations"
        },
        "text" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "BaseContent" : {
      "type" : "object",
      "properties" : {
        "text" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "Packshot" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "url" : {
          "$ref" : "#/definitions/Url"
        },
        "cdn_url" : {
          "$ref" : "#/definitions/Url"
        },
        "quantity" : {
          "$ref" : "#/definitions/Quantity"
        },
        "created_on" : {
          "$ref" : "#/definitions/Date"
        }
      }
    },
    "ArticleWine" : {
      "type" : "object",
      "properties" : {
        "country" : {
          "$ref" : "#/definitions/Country"
        },
        "region" : {
          "$ref" : "#/definitions/Region"
        },
        "type" : {
          "$ref" : "#/definitions/WineType"
        },
        "online_specials" : {
          "$ref" : "#/definitions/OnlineSpecials"
        },
        "year" : {
          "$ref" : "#/definitions/Year"
        },
        "fits_with" : {
          "$ref" : "#/definitions/Translations"
        },
        "varietal" : {
          "$ref" : "#/definitions/Translations"
        },
        "character" : {
          "$ref" : "#/definitions/Translations"
        },
        "temperature" : {
          "$ref" : "#/definitions/Translations"
        },
        "awards" : {
          "$ref" : "#/definitions/Translations"
        },
        "storage" : {
          "$ref" : "#/definitions/Translations"
        },
        "rating" : {
          "$ref" : "#/definitions/Rating"
        },
        "shop" : {
          "$ref" : "#/definitions/WineShop"
        },
        "box" : {
          "$ref" : "#/definitions/WineBox"
        }
      }
    },
    "WineShop" : {
      "type" : "object",
      "properties" : {
        "url" : {
          "$ref" : "#/definitions/Url"
        },
        "stock" : {
          "$ref" : "#/definitions/Stock"
        },
        "quantity" : {
          "$ref" : "#/definitions/Quantity"
        },
        "prices" : {
          "$ref" : "#/definitions/ArticlePrices"
        },
        "discount" : {
          "$ref" : "#/definitions/Translations"
        },
        "packshot" : {
          "$ref" : "#/definitions/Packshot"
        }
      }
    },
    "Region" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "WineType" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Navision wine type code",
          "minimum" : 0.0
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "Rating" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "number",
          "format" : "float",
          "description" : "Rating value",
          "minimum" : 0.0,
          "maximum" : 5.0
        },
        "total" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Ratng count",
          "minimum" : 0.0
        },
        "valid" : {
          "type" : "boolean",
          "description" : "Is a valid rating?"
        }
      }
    },
    "Stock" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Navision stock count, might be negative"
        },
        "code" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Navision stock code",
          "minimum" : 0.0
        },
        "message" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "Barcode" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "string",
          "description" : "Barcode text value (pattern according to type)"
        },
        "type" : {
          "type" : "string",
          "description" : "Barcode type code (e.g. 'EAN13', 'UPC12', 'ITF14', 'EAN8', 'PLU')"
        },
        "quantity" : {
          "$ref" : "#/definitions/Quantity"
        },
        "master" : {
          "type" : "boolean",
          "description" : "Is master barcode?"
        }
      }
    },
    "WineBox" : {
      "type" : "object",
      "properties" : {
        "code" : {
          "type" : "string",
          "description" : "Denner box type code (e.g. 'KA', 'HA', 'HB')",
          "pattern" : "/^[A-Z]{2}$/"
        },
        "batch_size" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Batch size",
          "minimum" : 0.0
        }
      }
    },
    "AssignedOnlineGroup" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "code" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Navision online group code"
        },
        "disabled" : {
          "type" : "boolean",
          "description" : "Is the group disabled?"
        },
        "allow_featuring" : {
          "type" : "boolean",
          "description" : "Does the group allow the assigned articles to be featured (i.e. displayed on front/main/home page)?"
        },
        "allow_promotion" : {
          "type" : "boolean",
          "description" : "Does the group allow the assigned articles to be promoted (i.e. displayed on a promotional page)?"
        },
        "allow_background" : {
          "type" : "boolean",
          "description" : "Does the group allow the assigned articles to be displayed with a background (i.e. displayed on a page with a deceptive/trivializing background)?"
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        },
        "parent" : {
          "$ref" : "#/definitions/AssignedOnlineGroup"
        }
      }
    },
    "OnlineSpecial" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Unique ID"
        },
        "sort_index" : {
          "$ref" : "#/definitions/SortIndex"
        },
        "title" : {
          "$ref" : "#/definitions/Translations"
        }
      }
    },
    "Appraisal" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "created_on" : {
          "type" : "string",
          "format" : "date-time",
          "description" : "Timestamp"
        },
        "wine_year" : {
          "$ref" : "#/definitions/Year"
        },
        "title" : {
          "type" : "string",
          "description" : "Title"
        },
        "description" : {
          "type" : "string",
          "description" : "Description"
        },
        "rating" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Given rating",
          "minimum" : 1.0,
          "maximum" : 5.0
        },
        "display_name" : {
          "type" : "string",
          "description" : "Person's (public) name"
        },
        "city" : {
          "type" : "string",
          "description" : "Person's city"
        },
        "language" : {
          "type" : "string",
          "description" : "Locale"
        }
      }
    },
    "NewAppraisal" : {
      "type" : "object",
      "required" : [ "address", "city", "email", "firstname", "gender", "language", "lastname", "rating", "title", "zip_code" ],
      "properties" : {
        "wine_year" : {
          "$ref" : "#/definitions/Year"
        },
        "title" : {
          "type" : "string",
          "description" : "Title"
        },
        "description" : {
          "type" : "string",
          "description" : "Description"
        },
        "rating" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Given rating",
          "minimum" : 1.0,
          "maximum" : 5.0
        },
        "firstname" : {
          "type" : "string",
          "description" : "Person's first name"
        },
        "lastname" : {
          "type" : "string",
          "description" : "Person's last name"
        },
        "address" : {
          "type" : "string",
          "description" : "Person's address"
        },
        "zip_code" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Person's ZIP code",
          "minimum" : 1000.0,
          "maximum" : 9699.0
        },
        "city" : {
          "type" : "string",
          "description" : "Person's city"
        },
        "email" : {
          "type" : "string",
          "description" : "Person's email address"
        },
        "gender" : {
          "type" : "string",
          "description" : "Person's gender (either \"male\" or \"female\")"
        },
        "shop_user_id" : {
          "type" : "integer",
          "description" : "Identifier for the person's Wineshop user account"
        },
        "language" : {
          "type" : "string",
          "description" : "Locale"
        }
      },
      "example" : {
        "application/json" : {
          "wine_year" : 2013,
          "title" : "un très très bon vin",
          "description" : "mais ce n'est pas du zinfandel !! c'est du PRIMITIVO !! Denner, qu'est ce qui vous arrive ???",
          "rating" : 5,
          "firstname" : "Isabelle",
          "lastname" : "Rossetti",
          "address" : "3 rue du Temple",
          "zip_code" : "1304",
          "city" : "Cossonay",
          "email" : "email@gmx.ch",
          "gender" : "female",
          "language" : "fr"
        }
      }
    },
    "SweepstakeParticipant" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "#/definitions/UUIDv4"
        },
        "created_on" : {
          "type" : "string",
          "format" : "date-time",
          "description" : "Timestamp"
        },
        "display_name" : {
          "type" : "string",
          "description" : "Person's (public) name"
        },
        "city" : {
          "type" : "string",
          "description" : "Person's city"
        },
        "language" : {
          "type" : "string",
          "description" : "Locale"
        }
      }
    },
    "NewSweepstakeParticipant" : {
      "type" : "object",
      "required" : [ "address", "city", "email", "firstname", "gender", "language", "lastname", "zip_code" ],
      "properties" : {
        "firstname" : {
          "type" : "string",
          "description" : "Person's first name"
        },
        "lastname" : {
          "type" : "string",
          "description" : "Person's last name"
        },
        "address" : {
          "type" : "string",
          "description" : "Person's address"
        },
        "zip_code" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Person's ZIP code",
          "minimum" : 1000.0,
          "maximum" : 9699.0
        },
        "city" : {
          "type" : "string",
          "description" : "Person's city"
        },
        "email" : {
          "type" : "string",
          "description" : "Person's email address"
        },
        "gender" : {
          "type" : "string",
          "description" : "Person's gender (either \"male\" or \"female\")"
        },
        "shop_user_id" : {
          "type" : "integer",
          "description" : "Identifier for the person's Wineshop user account"
        },
        "language" : {
          "type" : "string",
          "description" : "Locale"
        }
      },
      "example" : {
        "application/json" : {
          "firstname" : "Michelle",
          "lastname" : "Muster",
          "address" : "Bahnhofstrasse 7",
          "zip_code" : "8034",
          "city" : "Zurich",
          "email" : "email@gmx.ch",
          "gender" : "female",
          "shop_user_id" : 123456789,
          "language" : "de"
        }
      }
    },
    "Translations" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/Translation"
      }
    },
    "EcoLabels" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/EcoLabel"
      }
    },
    "Barcodes" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/Barcode"
      }
    },
    "Articles" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/Article"
      }
    },
    "OnlineSpecials" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/OnlineSpecial"
      }
    },
    "Appraisals" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/Appraisal"
      }
    },
    "ArticlesResponse" : {
      "type" : "object",
      "properties" : {
        "page_count" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The number of pages"
        },
        "page_size" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The page size"
        },
        "total_items" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The number of items on all pages"
        },
        "articles" : {
          "$ref" : "#/definitions/Articles"
        }
      }
    },
    "AppraisalsResponse" : {
      "type" : "object",
      "properties" : {
        "total_appraisals" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The number of items on all pages"
        },
        "appraisals" : {
          "$ref" : "#/definitions/Appraisals"
        }
      }
    }
  },
  "parameters" : {
    "PageParam" : {
      "name" : "page",
      "in" : "query",
      "description" : "The page number. Default: 1\n",
      "required" : false,
      "type" : "integer",
      "default" : 1,
      "minimum" : 0.0,
      "format" : "int32"
    },
    "PageSizeParam" : {
      "name" : "page_size",
      "in" : "query",
      "description" : "The page size. Default: 10\nTo disable pagination (when supported) send \"-1\".\n",
      "required" : false,
      "type" : "integer",
      "default" : 10,
      "format" : "int32"
    },
    "ArticleIdPathParam" : {
      "name" : "article_id",
      "in" : "path",
      "description" : "The unique identifier of an article",
      "required" : true,
      "type" : "string",
      "pattern" : "/^\\d{6}$/"
    },
    "FilterParam" : {
      "name" : "filter",
      "in" : "query",
      "description" : "Filters: JSON array of Filter object, urlencoded.\n\nFilter object:\n- property: Property to filter on.\n- operator: Operation property. Enumeration ('eq', 'like', 'lt', 'gt', 'in', ...). Dependent from property (not all might be allowed).\n- type: Type of value. Enumeration ('string', 'integer', 'boolean', 'array') Dependent from property and operator (not all might be allowed).\n- value: Value. Must be of the defined type.\n\nExamples:\n- [{\"property\":\"id\",\"operator\":\"in\",\"type\":\"array\",\"value\":[\"7627150d-36bd-4867-89b2-091800a03d24\",\"58afec5c-ece9-4b66-bc55-00d6dc1b65b8\"]}]\n- [{\"property\":\"in_shop\",\"operator\":\"eq\",\"type\":\"boolean\",\"value\":true}]\n",
      "required" : false,
      "type" : "string"
    },
    "AcceptHeader" : {
      "name" : "Accept",
      "in" : "header",
      "description" : "Accepted content type (supported is \"application/json\")\n",
      "required" : false,
      "type" : "string",
      "default" : "application/json"
    },
    "ContentTypeHeader" : {
      "name" : "Content-Type",
      "in" : "header",
      "description" : "Request body content type (supported is \"application/json\")\n",
      "required" : false,
      "type" : "string",
      "default" : "application/json"
    }
  }
}